package com.hermes.model.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.hermes.model.Board;
import com.hermes.model.ItemBoard;
import com.hermes.model.Version;
import com.hermes.model.Word;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordDaoConfig;
    private final DaoConfig boardDaoConfig;
    private final DaoConfig itemBoardDaoConfig;
    private final DaoConfig versionDaoConfig;

    private final WordDao wordDao;
    private final BoardDao boardDao;
    private final ItemBoardDao itemBoardDao;
    private final VersionDao versionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        boardDaoConfig = daoConfigMap.get(BoardDao.class).clone();
        boardDaoConfig.initIdentityScope(type);

        itemBoardDaoConfig = daoConfigMap.get(ItemBoardDao.class).clone();
        itemBoardDaoConfig.initIdentityScope(type);

        versionDaoConfig = daoConfigMap.get(VersionDao.class).clone();
        versionDaoConfig.initIdentityScope(type);

        wordDao = new WordDao(wordDaoConfig, this);
        boardDao = new BoardDao(boardDaoConfig, this);
        itemBoardDao = new ItemBoardDao(itemBoardDaoConfig, this);
        versionDao = new VersionDao(versionDaoConfig, this);

        registerDao(Word.class, wordDao);
        registerDao(Board.class, boardDao);
        registerDao(ItemBoard.class, itemBoardDao);
        registerDao(Version.class, versionDao);
    }
    
    public void clear() {
        wordDaoConfig.getIdentityScope().clear();
        boardDaoConfig.getIdentityScope().clear();
        itemBoardDaoConfig.getIdentityScope().clear();
        versionDaoConfig.getIdentityScope().clear();
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public BoardDao getBoardDao() {
        return boardDao;
    }

    public ItemBoardDao getItemBoardDao() {
        return itemBoardDao;
    }

    public VersionDao getVersionDao() {
        return versionDao;
    }

}
